name: ${project.name}
version: ${project.version}
main: nl.scoutcraft.eagle.limbo.EagleLimbo
api-version: 1.16
description: ${project.description}
authors: [ Acixsi, Daniel12321 ]
website: https://scoutcraft.nl